### ISSUE TITLE
Unable to read PDF

### ISSUE THREAD

**Issue by vikashrk** [ibmwtx/PDF#2]
Hi,

I have a PDF downloaded from IBM site. When I try to Import, the adapter is creating the XSD, with out parsing the PDF.

All I get to see in the XSD is below

<?xml version="1.0" encoding="utf-8"?><xs:schema xmlns:root="http://www.ibm.com/wtx/PDF" targetNamespace="http://www.ibm.com/wtx/PDF" xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:element name="Document">xs:complexTypexs:sequence<xs:element name="Properties">xs:complexTypexs:sequence<xs:element name="PageCount" type="xs:string" minOccurs="0" maxOccurs="1"/><xs:element name="Subject" type="xs:string"  minOccurs="0" maxOccurs="1"/><xs:element name="Producer" type="xs:string"  minOccurs="0" maxOccurs="1"/><xs:element name="Creator" type="xs:string"  minOccurs="0" maxOccurs="1"/><xs:element name="CreationDate" type="xs:string"  minOccurs="0" maxOccurs="1"/><xs:element name="Title" type="xs:string"  minOccurs="0" maxOccurs="1"/>/xs:sequence/xs:complexType/xs:element/xs:sequence/xs:complexType/xs:element/xs:schema

Attached the PDF for your reference. 
Request to let me know if the adapter only reads if the PDF document has filling fields.

Thanks,

[WSTE_WTX_Utility_Commands_part1_final.pdf](https://github.com/ibmwtx/PDF/files/133834/WSTE_WTX_Utility_Commands_part1_final.pdf)

**Comment by ibmwtx** [comment]
Currently, the adapter reads on Acro-forms. It does not read plain text or images. I have plans to add support for text in near future to read a page or group of pages, but no intention to support images. The process is  a) importer creates a schema b) Schema is used as a meta-data on the input card, with PDF adapter.  c) Adapter reads the fields in the acro-forms and formats to XML and presented to the input card for parsing.

**Comment by vikashrk** [comment]
Thank you for the update. 

When would the new feature to read plain text will be available?

Can I help you implement this feature? Please let me know what I should do. 

Thanks

Ramakrishna

**Comment by ibmwtx** [comment]
By end of Feb, I will have the support

**Comment by vikashrk** [comment]
Thank you.

Appreciate your help.

Ramakrishna

**Comment by vikashrk** [comment]
Hi,

Checking with you on the support for PDF import for PDF files.

Thanks.

**Comment by ibmwtx** [comment]
Added Support for Reading Page(s) from a PDF Document  for v8.4.1 and v9.0

**Comment by vikashrk** [comment]
Hi,

Thank you. I have downloaded for ITX v9.0 and tried to test. Below  are the issues I find
1) When I execute the map "BlobToText.mmc", I got the error as "Source not available" for adapter "Adobe PDF" and Command "-U wtxredbook.pdf -PAGE 22-23"
2) I used the file adapter in the first input card, to load the PDF file "wtxredbook.pdf" and used to the input in the first output card using the mapping rule "=PARSE(GET("PDF", "-PAGE 22-23 -T", Input))".
The output was generated, but the output looks like below
"<?xml version="1.0" encoding="UTF-8"?><wtxpdf:Document  xmlns:wtxpdf="http://www.ibm.com/wtx/PDF" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/wtx/PDF null"><Properties><PageCount>778</PageCount><Producer>Acrobat Distiller 7.0.5 (Windows)</Producer><Creator>FrameMaker 8.0</Creator><CreationDate></CreationDate><Title>IBM WebSphere Transformation Extender 8.2</Title></Properties>"

I don't see the text from Page 22 and 23.
4) I tried to enable the TRACE command using -T and I don't see any m4pdf.mtr file generated.

Attached the PI, which has the maps I tested. Also attached the configuration I have done based on readme.md file. The PI also has the PDF "
[Configuration in my system and map screen print.docx](https://github.com/ibmwtx/PDF/files/155433/Configuration.in.my.system.and.map.screen.print.docx)
[Test_PDF.zip](https://github.com/ibmwtx/PDF/files/155434/Test_PDF.zip)

" which I am planning to parse and use

Hope these issues with be resolved.

Thanks for all your help.

**Comment by ibmwtx** [comment]
Uploaded a new fix for the GET function.

**Comment by vikashrk** [comment]
Thank you for providing the fix.

I tested after the fix and now the output do not have any information. Its a 0byte file with no data at all.

Below is use

=PARSE(GET("PDF","-PAGE 22-23",Input))

**Comment by ibmwtx** [comment]
a) Remove the PARSE. I am unable to repeat the issue. 

Do you have m4pdf.jar along with PDFBox.jar in the ITX Install Directory . 

Can you Turn on -T on the adapter and also in the dtx.ini , enable the following section

[JNI Layer Trace]
switch=on
file=c:\dtxjni.log
;pid=on
level=30

and capture the logs and check what the error is ?

**Comment by vikashrk** [comment]
Hi,
Thanks for the response.
I am using ITX v9.0. the file copied to DTX_INSTALL are "m4pdf.jar" and "pdfbox-1.8.11.jar"
Attached the document which shows the configuration in my environment "Below is the configuration in my environment.docx"
Attached the dtxjni.log file "dtxjni.log_9408"
Attached the PI "PDFInbound_Read.zip"

Need your help to resolve the issue.

Thanks again

[Below is the configuration in my environment.docx](https://github.com/ibmwtx/PDF/files/157506/Below.is.the.configuration.in.my.environment.docx)
[PDFInbound_Read.zip](https://github.com/ibmwtx/PDF/files/157510/PDFInbound_Read.zip)
[dtxjni.log_9408.log.txt](https://github.com/ibmwtx/PDF/files/157516/dtxjni.log_9408.log.txt)

**Comment by vikashrk** [comment]
Hi,

I successfully resolved the issue.

**Below are the steps which did not work**
1) Download the JAR file pdfbox-1.8.11.jar from https://pdfbox.apache.org/download.cgi
2) Copied the JAR pdfbox-1.8.11.jar, m4pdf.jar to WTX_INSTALL directory
3) Copied the JAR's com.ibm.websphere.dtx.ui.importers.pdf.nl_Version.jar, com.ibm.websphere.dtx.ui.importers.pdf.version.jar to "WTX INSTALL"\DesignStudio\wtx_eclipse\eclipse\plugins "
4) executed "CleanExtenderStudio.bat".
5) DesignStudio opened and executed the map.
6) Map did not generate any output. JNI log file generated and I see the error "<8516-14360-03/03/16 15:07:38>: *ERR: java.lang.NoClassDefFoundError: org.apache.pdfbox.pdfparser.PDFParser (initialization failure)"
7) renamed the file pdfbox-1.8.11.jar to "pdfbox.jar".
8) Executed "CleanExtenderStudio.bat".
9) DesignStudio opened and executed the map.
10) Map did not generate any output. JNI log file generated and I see the error "<3976-11344-03/03/16 15:11:09>:    *ERR: java.lang.NoClassDefFoundError: org.apache.commons.logging.LogFactory"

**Below are the steps resolved the problem**
1) Download the JAR file pdfbox-app-1.8.11.jar from https://pdfbox.apache.org/download.cgi
2) Copied the JAR pdfbox-app-1.8.11.jar, m4pdf.jar to WTX_INSTALL directory
3) Copied the JAR's com.ibm.websphere.dtx.ui.importers.pdf.nl_Version.jar, com.ibm.websphere.dtx.ui.importers.pdf.version.jar to "WTX INSTALL"\DesignStudio\wtx_eclipse\eclipse\plugins "
4) executed "CleanExtenderStudio.bat".
5) DesignStudio opened and executed the map.
6) This time, map successfuly executed successfully and produced the output.

**_Request to update the below statment in README.MD file

d) Download Apache PDFBox artifacts from PDFBox version 1.8.x Copy pdfbox-xxx.jar to "WTX INSTALL DIR" 

change to 

d) Download Apache PDFBox artifacts from PDFBox version 1.8.x Copy pdfbox-app-xxx.jar to "WTX INSTALL DIR"_**

**Comment by vikashrk** [comment]
There is one more issue, still.
1) -T is still not generating the trace file
GET("PDF", " -T -PAGE 22-23", Input)

request to resolve.

**Comment by vikashrk** [comment]
Hi,

Thank you for all your help. I hope this adapter will be rolled into ITX new version as a new feature.

I have been working with ITX since it was Mercator V5. I have worked on almost all version, and also contributed in WTX Forums. I have even written custom functions in WTX introduced in 8.1.

*_I am interested in learning and writing new adapters and contribute to forums and GIT/ibmwtx.
Request you to direct me any document on how to write custom adapters using WTX.
*_

summarize the defects and new ask
1) Trace file not getting generated GET("PDF", " -T -PAGE 22-23", Input)

New Ask
1) request to generate XML if possible.
2) I see that PDFBox API can export a HTML, if XML is not possible, can you generate a HTML output.

Thanks for all your help.

Regards,
Ram

**Comment by ibmwtx** [comment]
Uploaded Source code for the PDF Adapter

**Comment by vikashrk** [comment]
Thank you.

Does the fix include trace file generation?

Does the fox include export to XML or HTML?

Please let me know

Thanks

Regards,
Ram

**Comment by ibmwtx** [comment]
Fixed the Trace file generation issue. Updated the jars and the source code

**Comment by vikashrk** [comment]
Hi,

Thanks for fixing the issue. But the source code and JAR file is not uploaded yet.

Request to upload.

Thanks.

**Comment by ibmwtx** [comment]
I uploaded both on the weekend. m4pdf.jar and the xxxcommanline.java

**Comment by RDevt** [comment]
Hi, i have wtx 9.0 version and have downloaded all the latest jar files and followed this readme, but still getting source not available for my pdf, please help.

**Comment by NalamSubramanyam** [comment]
Hi Vikashrk,

I am getting the same error as you faced . Source not available . Can you help me with the reason for it . Below is the log file . 

<2992-4340-03/07/17 22:21:11>:	===== WebSphere Transformation Extender Java Programming Interface Library =====
<2992-4340-03/07/17 22:21:11>:	Version: 8.4.1.2(4)
<2992-4340-03/07/17 22:21:11>:	Install Directory: C:\IBM\WebSphere Transformation Extender 8.4.1\
<2992-4340-03/07/17 22:21:11>:	CLASSPATH: null
<2992-4340-03/07/17 22:21:11>:	Loading JVM...
<2992-4340-03/07/17 22:21:11>:	JVM already loaded. Path: C:\IBM\WebSphere Transformation Extender 8.4.1\java\bin\j9vm\jvm.dll
<2992-4340-03/07/17 22:21:11>:	Loading JVM symbols...
<2992-4340-03/07/17 22:21:11>:	JVM symbols loaded successfully.
<2992-4340-03/07/17 22:21:11>:	JVM exists with ptr = 0046E910, count = 1
<2992-4340-03/07/17 22:21:11>:	Message Broker Environment not detected based on environment variable, MQSI_VERSION.
<2992-4340-03/07/17 22:21:11>:	WARN: Unable to retrieve class for jni env: 23629C00, class: com/ibm/websphere/dtx/m4pdf
<2992-4340-03/07/17 22:21:11>:	WARN: Unable to retrieve class for jni env: 23629C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-4340-03/07/17 22:21:11>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:21:24>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:21:24>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:21:24>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:21:38>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:21:38>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:21:38>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:23:00>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:23:00>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:23:00>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:25:46>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:25:46>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:25:46>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-7976-03/07/17 22:25:52>:	WARN: Unable to retrieve class for jni env: 26C02600, class: com/ibm/websphere/dtx/m4excel
<2992-5416-03/07/17 22:25:55>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4excel
<2992-5416-03/07/17 22:25:55>:	Initializing Adapter Library...
<2992-5416-03/07/17 22:25:55>:	Time stamp: 03/07/17 22:25:55
<2992-5416-03/07/17 22:25:55>:	Adapter Library initialized successfully.
<2992-5416-03/07/17 22:25:55>:	Creating adapter instance...
<2992-5416-03/07/17 22:25:55>:	ID = 22
<2992-5416-03/07/17 22:25:55>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4excel
<2992-5416-03/07/17 22:25:55>:	Global ref added in Ensure: pEnv=02436C00, ref=02451D54, count=1, type=4098
<2992-5416-03/07/17 22:25:55>:	Global ref added in Set   : pEnv=02436C00, ref=02451D58, count=2
<2992-5416-03/07/17 22:25:55>:	Adapter instance created successfully.
<2992-5416-03/07/17 22:25:55>:	Global ref added in Ensure: pEnv=02436C00, ref=02451D5C, count=3, type=4097
<2992-5672-03/07/17 22:25:55>:	Creating connection instance...
<2992-5672-03/07/17 22:25:55>:	ID = 28
<2992-5672-03/07/17 22:25:55>:	Connection instance created successfully.
<2992-5672-03/07/17 22:25:55>:	WARN: Unable to retrieve class for jni env: 23321800, class: com/ibm/websphere/dtx/m4excel
<2992-5672-03/07/17 22:25:55>:	Global ref added in Set   : pEnv=23321800, ref=02451D60, count=1
<2992-5672-03/07/17 22:25:56>:	Global ref added in Ensure: pEnv=23321800, ref=02451D64, count=2, type=10
<2992-5416-03/07/17 22:25:56>:	Creating adapter instance...
<2992-5416-03/07/17 22:25:56>:	ID = 30
<2992-5416-03/07/17 22:25:56>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4excel
<2992-5416-03/07/17 22:25:56>:	Global ref added in Ensure: pEnv=02436C00, ref=02451D68, count=4, type=4098
<2992-5416-03/07/17 22:25:56>:	Global ref added in Set   : pEnv=02436C00, ref=02451D6C, count=5
<2992-5416-03/07/17 22:25:56>:	Adapter instance created successfully.
<2992-5672-03/07/17 22:25:56>:	Global ref added in Ensure: pEnv=23321800, ref=02451D70, count=3, type=10
<2992-5672-03/07/17 22:25:56>:	Global ref removed in stop: max was = 3, count now = 2, ref=02451D70, event=4
<2992-5672-03/07/17 22:25:56>:	Global ref removed in stop: max was = 3, count now = 1, ref=02451D64, event=4
<2992-5416-03/07/17 22:25:56>:	Destroying adapter instance
<2992-5416-03/07/17 22:25:56>:	ID = 30
<2992-5416-03/07/17 22:25:56>:	Global ref deleted in RJI : max was = 5, count now = 5, ref=02451D54, javainst_ref=02451D70
<2992-5416-03/07/17 22:25:56>:	Global ref deleted in RJI : max was = 5, count now = 4, ref=02451D6C, main_ref=1
<2992-5416-03/07/17 22:25:56>:	Adapter instance destroyed successfully.
<2992-5416-03/07/17 22:25:56>:	Global ref deleted in RJI : max was = 4, count now = 3, ref=02451D68, main_ref=0
<2992-5416-03/07/17 22:25:56>:	Destroying adapter instance
<2992-5416-03/07/17 22:25:56>:	ID = 22
<2992-5416-03/07/17 22:25:56>:	Global ref deleted in RJI : max was = 3, count now = 3, ref=02451D54, javainst_ref=02451D64
<2992-5416-03/07/17 22:25:56>:	Global ref deleted in RJI : max was = 3, count now = 2, ref=02451D58, main_ref=0
<2992-5416-03/07/17 22:25:56>:	Adapter instance destroyed successfully.
<2992-5416-03/07/17 22:25:56>:	Global ref deleted in RJI : max was = 2, count now = 1, ref=02451D54, main_ref=0
<2992-5416-03/07/17 22:25:56>:	Global ref deleted in RJI : max was = 1, count now = 0, ref=02451D5C, main_ref=0
<2992-5416-03/07/17 22:25:56>:	Not detaching current thread in RJI: pEnv=02436C00, bAttached=0, Java API invocation detected
<2992-5672-03/07/17 22:25:57>:	Destroying connection instance...
<2992-5672-03/07/17 22:25:57>:	ID = 28
<2992-5672-03/07/17 22:25:57>:	Global ref deleted in RJI : max was = 1, count now = 0, ref=02451D60, main_ref=1
<2992-5672-03/07/17 22:25:57>:	Connection instance destroyed successfully.
<2992-5416-03/07/17 22:25:57>:	Destroying library...
<2992-5416-03/07/17 22:25:57>:	Library destroyed successfully.
<2992-5416-03/07/17 22:26:12>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:26:12>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:26:12>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:26:20>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:26:20>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:26:20>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:27:10>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:27:10>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:27:10>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:35:54>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf
<2992-5416-03/07/17 22:35:54>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4pdf/MAdapterSettingsImpl
<2992-5416-03/07/17 22:35:54>:	*ERR: Function failed (-3) in dtxjpiGetConfig()
<2992-5416-03/07/17 22:36:05>:	Initializing Adapter Library...
<2992-5416-03/07/17 22:36:05>:	Time stamp: 03/07/17 22:36:05
<2992-5416-03/07/17 22:36:05>:	Adapter Library initialized successfully.
<2992-5416-03/07/17 22:36:05>:	Creating adapter instance...
<2992-5416-03/07/17 22:36:05>:	ID = 51
<2992-5416-03/07/17 22:36:05>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4excel
<2992-5416-03/07/17 22:36:05>:	Global ref added in Ensure: pEnv=02436C00, ref=02451D54, count=1, type=4098
<2992-5416-03/07/17 22:36:05>:	Global ref added in Set   : pEnv=02436C00, ref=02451D58, count=2
<2992-5416-03/07/17 22:36:05>:	Adapter instance created successfully.
<2992-5416-03/07/17 22:36:05>:	Global ref added in Ensure: pEnv=02436C00, ref=02451D5C, count=3, type=4097
<2992-9804-03/07/17 22:36:05>:	Creating connection instance...
<2992-9804-03/07/17 22:36:05>:	ID = 57
<2992-9804-03/07/17 22:36:05>:	Connection instance created successfully.
<2992-9804-03/07/17 22:36:05>:	WARN: Unable to retrieve class for jni env: 2A508300, class: com/ibm/websphere/dtx/m4excel
<2992-9804-03/07/17 22:36:05>:	Global ref added in Set   : pEnv=2A508300, ref=02451D60, count=1
<2992-9804-03/07/17 22:36:05>:	Global ref added in Ensure: pEnv=2A508300, ref=02451D64, count=2, type=10
<2992-5416-03/07/17 22:36:05>:	Creating adapter instance...
<2992-5416-03/07/17 22:36:05>:	ID = 59
<2992-5416-03/07/17 22:36:05>:	WARN: Unable to retrieve class for jni env: 02436C00, class: com/ibm/websphere/dtx/m4excel
<2992-5416-03/07/17 22:36:05>:	Global ref added in Ensure: pEnv=02436C00, ref=02451D68, count=4, type=4098
<2992-5416-03/07/17 22:36:05>:	Global ref added in Set   : pEnv=02436C00, ref=02451D6C, count=5
<2992-5416-03/07/17 22:36:05>:	Adapter instance created successfully.
<2992-9804-03/07/17 22:36:05>:	Global ref added in Ensure: pEnv=2A508300, ref=02451D70, count=3, type=10
<2992-9804-03/07/17 22:36:05>:	Global ref removed in stop: max was = 3, count now = 2, ref=02451D70, event=4
<2992-9804-03/07/17 22:36:05>:	Global ref removed in stop: max was = 3, count now = 1, ref=02451D64, event=4
<2992-5416-03/07/17 22:36:05>:	Destroying adapter instance
<2992-5416-03/07/17 22:36:05>:	ID = 59
<2992-5416-03/07/17 22:36:05>:	Global ref deleted in RJI : max was = 5, count now = 5, ref=02451D54, javainst_ref=02451D70
<2992-5416-03/07/17 22:36:05>:	Global ref deleted in RJI : max was = 5, count now = 4, ref=02451D6C, main_ref=1
<2992-5416-03/07/17 22:36:05>:	Adapter instance destroyed successfully.
<2992-5416-03/07/17 22:36:05>:	Global ref deleted in RJI : max was = 4, count now = 3, ref=02451D68, main_ref=0
<2992-5416-03/07/17 22:36:05>:	Destroying adapter instance
<2992-5416-03/07/17 22:36:05>:	ID = 51
<2992-5416-03/07/17 22:36:05>:	Global ref deleted in RJI : max was = 3, count now = 3, ref=02451D54, javainst_ref=02451D64
<2992-5416-03/07/17 22:36:05>:	Global ref deleted in RJI : max was = 3, count now = 2, ref=02451D58, main_ref=0
<2992-5416-03/07/17 22:36:05>:	Adapter instance destroyed successfully.
<2992-5416-03/07/17 22:36:05>:	Global ref deleted in RJI : max was = 2, count now = 1, ref=02451D54, main_ref=0
<2992-5416-03/07/17 22:36:05>:	Global ref deleted in RJI : max was = 1, count now = 0, ref=02451D5C, main_ref=0
<2992-5416-03/07/17 22:36:05>:	Not detaching current thread in RJI: pEnv=02436C00, bAttached=0, Java API invocation detected
<2992-9804-03/07/17 22:36:07>:	Destroying connection instance...
<2992-9804-03/07/17 22:36:07>:	ID = 57
<2992-9804-03/07/17 22:36:07>:	Global ref deleted in RJI : max was = 1, count now = 0, ref=02451D60, main_ref=1
<2992-9804-03/07/17 22:36:07>:	Connection instance destroyed successfully.
<2992-5416-03/07/17 22:36:07>:	Destroying library...
<2992-5416-03/07/17 22:36:07>:	Library destroyed successfully.

**Comment by sunil548** [comment]
Hi I am trying to execute the attached code using input PDF Adapter in ITX 9 but not able to read it.I am getting null pointer exception.Anyone please assist me

![m4pdf_Error](https://user-images.githubusercontent.com/64523712/80574270-2950c580-8a1f-11ea-989c-468e3b2ea5bc.jpg)


[PDF_POC.zip](https://github.com/ibmwtx/PDF/files/4550435/PDF_POC.zip)
